import * as ts from 'typescript'

ts.isAccessor
ts.isArrayBindingElement
ts.isArrayBindingPattern
ts.isArrayLiteralExpression
ts.isArrayTypeNode
ts.isArrowFunction
ts.isAsExpression
ts.isAssertionExpression
ts.isAssertsKeyword
ts.isAsteriskToken
ts.isAutoAccessorPropertyDeclaration
ts.isAwaitExpression
ts.isAwaitKeyword
ts.isBigIntLiteral
ts.isBinaryExpression
ts.isBinaryOperatorToken
ts.isBindingElement
ts.isBindingName
ts.isBlock
ts.isBreakOrContinueStatement
ts.isBreakStatement

ts.isCallChain
ts.isCallExpression
ts.isCallLikeExpression
ts.isCallOrNewExpression
ts.isCallSignatureDeclaration
ts.isCaseBlock
ts.isCaseClause
ts.isCaseOrDefaultClause
ts.isCatchClause
ts.isClassDeclaration
ts.isClassElement
ts.isClassExpression
ts.isClassLike
ts.isClassOrTypeElement
ts.isClassStaticBlockDeclaration
ts.isClassStaticBlockDeclaration
ts.isColonToken
ts.isCommaListExpression
ts.isComputedPropertyName
ts.isConciseBody
ts.isConditionalExpression
ts.isConditionalTypeNode
ts.isConstTypeReference
ts.isConstructSignatureDeclaration
ts.isConstructorDeclaration
ts.isConstructorTypeNode
ts.isContinueStatement
ts.isDebuggerStatement
ts.isDeclarationStatement
ts.isDecorator
ts.isDefaultClause
ts.isDeleteExpression
ts.isDoStatement
ts.isDotDotDotToken
ts.isElementAccessChain
ts.isElementAccessExpression
ts.isEmptyBindingElement
ts.isEmptyBindingPattern
ts.isEmptyStatement
ts.isEntityName
ts.isEnumDeclaration
ts.isEnumMember
ts.isEqualsGreaterThanToken
ts.isExclamationToken
ts.isExportAssignment
ts.isExportDeclaration
ts.isExportSpecifier
ts.isExpression
ts.isExpressionStatement
ts.isExpressionWithTypeArguments
ts.isExternalModule
ts.isExternalModuleNameRelative
ts.isExternalModuleReference
ts.isForInStatement
ts.isForInitializer
ts.isForOfStatement
ts.isForStatement
ts.isFunctionDeclaration
ts.isFunctionExpression
ts.isFunctionLike
ts.isFunctionOrConstructorTypeNode
ts.isFunctionTypeNode

ts.isVariableStatement

declare const varStatement: ts.VariableStatement

varStatement



ts.isBuildCommand
ts.isBundle

